- embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/runningServersOps.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala
- schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/EmbeddedKafkaWithSchemaRegistry.scala
- schema-registry/src/test/scala/net/manub/embeddedkafka/schemaregistry/EmbeddedKafkaWithSchemaRegistryObjectSpec.scala
> change isRunning implementations and fix servers stopping order

- .travis.yml
- build.sbt
- project/plugins.sbt
> CI release

- README.md
- build.sbt
- project/plugins.sbt
also disable artifact publishing on root project
> remove sbt-bintray plugin

- build.sbt
hopefully will fix the publishing error
> set Gigahorse to false

- .travis.yml
override default script in test stage
> add sbt sonatypeReleaseAll to release stage script

- .travis.yml
- build.sbt
- project/build.properties
Bumped a bunch of dependencies.
> Versions bump

- build.sbt
> redefine release process

- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/AdminOps.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
> add AdminOps.deleteTopics

- .travis.yml
- build.sbt
To fix TravisCI build problems as per travis-ci/travis-ci#10290
> switch to openjdk8

- README.md
- build.sbt
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ConsumerExtensions.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/Consumers.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedServer.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/UUIDs.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/avro/avroMarshallers.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/AdminOps.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/ConsumerOps.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/ProducerOps.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/kafkaOps.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/runningServersOps.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/zooKeeperOps.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/package.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/ConsumerExtensionsSpec.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaUnavailableSpec.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaWithRunningKafkaOnFoundPortSpec.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaWithRunningKafkaSpec.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/embeddedKafkaSpecSupport.scala
- kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreams.scala
- kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreamsAllInOne.scala
- kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedStreamsConfig.scala
- kafka-streams/src/test/scala/net/manub/embeddedkafka/streams/ExampleKafkaStreamsSpec.scala
also add scalatestplus mockito dependency
> bump scalatest dependency version to 3.1.0

- .travis.yml
- README.md
- build.sbt
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
also update README.md to reflect the new supported version
> add Scala 2.13 version to Travis descriptor

- embedded-kafka/src/main/scala/net/manub/embeddedkafka/avro/avroMarshallers.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/avro/package.scala
they didn't belong to this project anyway
> deprecate Avro classes

- embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala
> restore original values for default ports

- README.md
- build.sbt
> bump kafka version to 2.5.0

- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ops/kafkaOps.scala
> remove useless semi-private startKafka method

- README.md
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/ConsumerExtensions.scala
fix Scala version reference in deprecation annotation
> add deprecation note to README.md

- project/Dependencies.scala
bump scalatestplus mockito version
> import scalatest modules

- embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
- embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedServer.scala
- embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaCustomConfigSpec.scala
- project/Dependencies.scala
> bump Scala versions

- project/Dependencies.scala
bump Scala versions to match Kafka's
> bump Kafka version to 2.7.0

- .github/mergify.yml
- .github/workflows/coverage-report.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
also prevent undesired scala-library version bump
> fix mergify conditions

- project/plugins.sbt
> bump sbt-scoverage plugin to 1.7.0

- build.sbt
> use coverageMinimumStmtTotal

- embedded-kafka/src/test/scala/io/github/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
- project/Dependencies.scala
> bump Kafka version to 3.0.0

- embedded-kafka/src/main/scala/io/github/embeddedkafka/ops/kafkaOps.scala
fallback to `zookeeper.session.timeout.ms` value
Closes #286
> unset zookeeper.connection.timeout.ms

- project/Dependencies.scala
also bump scalatest to v.3.2.14
> bump kafka to v3.3.1

- kafka-connect/src/main/scala/io/github/embeddedkafka/connect/EmbeddedKafkaConnect.scala
- project/Dependencies.scala
> Bump Kafka to v3.4.0

- project/Dependencies.scala
> replace slf4j-log4j12 with slf4j-reload4j

- README.md
- build.sbt
- kafka-connect/src/main/scala/io/github/embeddedkafka/connect/EmbeddedKafkaConnect.scala
- kafka-streams/src/main/scala/io/github/embeddedkafka/streams/EmbeddedKafkaStreams.scala
- project/Dependencies.scala
Attempting to resolve: https://github.com/embeddedkafka/embedded-kafka/issues/411
> Cross-compile project to Scala 3

- .github/workflows/release.yml
- build.sbt
- version.sbt
Closes #455 introducing an automated way of releasing artifacts, i.e. creating releases from GitHub.
If this succeeds I'm going to apply the same changes to embedded-kafka-schema-registry as well.
> remove version.sbt and add versionScheme setting

- .github/workflows/release.yml
Let's go back and try to make Sonatype publish step work.
> Revert release.yml changes

- project/Dependencies.scala
This reverts commit 6f666de283e2a3fd45f9d6b44cac453143d64b00.
> Revert "Update slf4j-reload4j to 2.0.9 (#466)"

- .github/workflows/coverage-report.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
See https://github.com/actions/runner-images/issues/11350
> add setup-sbt step to fix workflows on ubuntu-24.04

- build.sbt
- project/build.properties
- project/plugins.sbt
Resolves https://github.com/embeddedkafka/embedded-kafka/issues/569
> 🏗️ build: publish to Sonatype Central

- embedded-kafka/src/test/scala/io/github/embeddedkafka/EmbeddedKafkaObjectSpec.scala
Port 7000 seems to clash with the mac Control Center so changing it to 9000
> Use mac friendly port
